# 1. Active Service (Stable Traffic)
apiVersion: v1
kind: Service
metadata:
  name: auto-rollback 
  namespace: {{ .Values.namespace }}
  labels:
    app: auto-rollback
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: auto-rollback 